########################################
##         The Travel Agency          ##
########################################

## Start the system with "docker-compose up -d"
## Shutdown it with "docker-compose down"
## To clean your docker install: "docker system prune"
## To purge your docker install: "docker system prune -a"


version: "3"

services:

  flight_booking:
      container_name: tta-flight-booking
      build:
            context: ../services/rpc
      ports:
        - "9090:8080"

  carrent_and_hotel_reservation:
    container_name: tta-car-and-hotel
    build:
      context: ../services/resource
    ports:
      - "9080:8080"

  booking_management:
    container_name: tta-booking
    build:
      context: ../services/document/
    depends_on:
      - tta-database
    ports:
     - "8080:8080"

  tta-database:
    container_name: tta-database
    image: mongo:3.0
    ports:
    - "27017:27017"
