########################################
##              TELEGRAM              ##
########################################

## Start the system with "docker-compose up -d"
## Shutdown it with "docker-compose down"
## To clean your docker install: "docker system prune"
## To purge your docker install: "docker system prune -a"


version: "3"

services:

  integration-bus:
      container_name: telegram-esb
      build:
        context: ./flows
      depends_on:
        - external-cars-service
        - internal-cars-service
        - external-flights-service
        - internal-flights-service
        - hotels-services
      ports:
        - "8181:8181"
        - "8101:8101"
        - "1099:1099"
        - "61616:61616"
        - "44444:44444"
        - "8989:8989"

  external-cars-service:
    container_name: telegram-cars-services
    build:
      context: ./external-services/cars
    ports:
      - "9080:8080"

  internal-cars-service:
    container_name: tta-car-services
    build:
      context: ../services/resource
    ports:
      - "9480:8080"

  external-flights-service:
    container_name: telegram-flights-services
    build:
      context: ./external-services/flights
    environment:
          - db_host=flights-database
          - db_port=27017
    depends_on:
      - flights-database
    links:
      - flights-database
    ports:
      - "9180:8080"

  internal-flights-service:
    container_name: tta-flight-services
    build:
          context: ../services/rpc
    ports:
      - "9380:8080"

  hotels-services:
    container_name: telegram-hotels-services
    build:
      context: ./external-services/hotels
    ports:
      - "9280:8080"

  flights-database:
    container_name: flights-database
    build:
      context: ../docker/flightdatabase
    ports:
      - "27017:27017"

  booking-management:
    container_name: tta-booking
    build:
      context: ./../services/document/
    depends_on:
      - tta-database
    ports:
       - "8080:8080"

  tta-database:
    container_name: tta-database
    image: mongo:3.0
    ports:
      - "28017:27017"